/**
 * Verified read-only adapter for Assay Yield (ERC-8004 BSC Mainnet 331752).
 *
 * The published service currently accepts GET, despite advertising A2A in its
 * ERC-8004 metadata. This adapter follows that observed public contract and
 * never turns the response into a quote, payment request, or transaction.
 */
import { TaskInputError } from '../agentExecutors.js';
import { getExternalAdapterKey } from '../agentCapabilities.js';

export const ASSAY_YIELD_ENDPOINT = 'https://assay-ten-iota.vercel.app/api/agents/yield';
export const ASSAY_YIELD_CARD_URL = `${ASSAY_YIELD_ENDPOINT}/card`;
const ADDRESS_RE = /^0x[a-fA-F0-9]{40}$/;
const TIMEOUT_MS = 15_000;

function fail(message) {
  throw new TaskInputError(message);
}

function parseMarkets(input) {
  const raw = input?.markets;
  if (raw == null || String(raw).trim() === '') return [];
  const markets = String(raw).split(',').map((value) => value.trim()).filter(Boolean);
  if (markets.length > 20) fail('Assay Yield accepts at most 20 vToken addresses.');
  for (const address of markets) {
    if (!ADDRESS_RE.test(address)) fail(`The vToken address "${address.slice(0, 24)}" is invalid.`);
  }
  return markets;
}

async function request(input) {
  const markets = parseMarkets(input);
  const url = new URL(ASSAY_YIELD_ENDPOINT);
  if (markets.length) url.searchParams.set('markets', markets.join(','));

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const response = await fetch(url, { headers: { accept: 'application/json' }, signal: controller.signal });
    const raw = await response.text();
    let body;
    try { body = JSON.parse(raw); } catch { fail('Assay Yield returned malformed JSON.'); }
    if (!response.ok) fail(`Assay Yield returned HTTP ${response.status}.`);
    return { body, url: url.toString() };
  } catch (err) {
    if (err instanceof TaskInputError) throw err;
    if (err?.name === 'AbortError') fail('Assay Yield did not respond within 15 seconds.');
    fail(`Assay Yield could not be reached: ${err.message}`);
  } finally {
    clearTimeout(timer);
  }
}

function validate(body) {
  if (!body || body.agent !== 'Assay Yield' || !Array.isArray(body.markets)) {
    fail('Assay Yield returned an unsupported result shape.');
  }
  if (!Number.isFinite(Number(body.block)) || Number.isNaN(Date.parse(body.at))) {
    fail('Assay Yield returned no valid block or timestamp.');
  }
  for (const market of body.markets) {
    if (!market || typeof market.market !== 'string' || !ADDRESS_RE.test(String(market.address || '')) || !Number.isFinite(Number(market.supplyApy))) {
      fail('Assay Yield returned a malformed market row.');
    }
  }
}

function externalCell(value, opts = {}) {
  return { value: String(value), source: 'external', ...opts };
}

export async function executeAssayYield({ agent, execution }) {
  if (getExternalAdapterKey(agent) !== 'assay-yield') fail('This is not the verified Assay Yield agent.');
  const { body, url } = await request(execution.input || {});
  validate(body);
  const markets = parseMarkets(execution.input || {});
  const rows = body.markets.map((market) => ({
    market: externalCell(market.market, { note: market.address }),
    address: externalCell(market.address),
    supplyApy: externalCell(`${market.supplyApy}%`),
  }));
  return {
    headline: body.verdict || `Assay Yield returned ${body.markets.length} live markets`,
    summary: `Assay Yield returned live Venus supply-market data through an external HTTP service at BSC Mainnet block #${body.block}. This was a read-only task; no AgentHub RPC call or blockchain transaction was made.`,
    fields: [
      { key: 'agent', label: 'External agent', value: body.agent, source: 'external' },
      { key: 'markets', label: 'Markets returned', value: String(body.markets.length), source: 'external' },
      { key: 'requestedMarkets', label: 'Requested markets', value: markets.length ? markets.join(', ') : 'Agent default set', source: markets.length ? 'input' : 'external' },
      { key: 'block', label: 'BSC Mainnet block', value: `#${Number(body.block).toLocaleString('en-US')}`, source: 'external' },
      { key: 'readAt', label: 'External read at', value: body.at, source: 'external' },
      { key: 'source', label: 'Agent-reported source', value: body.source || 'Not reported', source: body.source ? 'external' : 'unavailable' },
    ],
    tables: [{
      title: 'Assay Yield result',
      note: 'Values are copied from the verified external response; no yield or payment estimate was generated by AgentHub.',
      columns: [
        { key: 'market', label: 'Market' },
        { key: 'address', label: 'vToken address' },
        { key: 'supplyApy', label: 'Supply APY' },
      ],
      rows,
    }],
    warnings: ['This is external HTTP/A2A-advertised service output, not a BSC RPC read and not a deposit recommendation.'],
    recommendation: 'Read-only market information returned. No funds were moved, signed, or broadcast.',
    hasSimulated: false,
    provenance: {
      source: 'external-http-a2a',
      transport: 'external-http',
      endpoint: ASSAY_YIELD_ENDPOINT,
      metadataUrl: ASSAY_YIELD_CARD_URL,
      chainId: 56,
      network: 'BSC Mainnet',
      blockNumber: Number(body.block),
      readAt: body.at,
      explorer: 'https://bscscan.com',
    },
    rawResponse: body,
    reads: [{ method: 'HTTP GET', target: url, status: 200 }],
  };
}

export const assayYieldAdapter = Object.freeze({
  kind: 'execution',
  adapterKey: 'assay-yield',
  endpoint: ASSAY_YIELD_ENDPOINT,
  chainId: 56,
  canHandle: (agent) => getExternalAdapterKey(agent) === 'assay-yield',
  execute: executeAssayYield,
});
